name: Docker AIService
on:
  workflow_call: {}
  workflow_dispatch: {}
  release:
    types:
      - released
jobs:
  docker-web:
    name: Docker Web
    uses: ./.github/workflows/reusable-docker-build.yml
    secrets: inherit
    with:
      repository: onebrief/langfuse-ob-web
      dockerfile: web/Dockerfile
      context: .

  docker-worker:
    name: Docker Worker  
    uses: ./.github/workflows/reusable-docker-build.yml
    secrets: inherit
    with:
      repository: onebrief/langfuse-ob-worker
      dockerfile: worker/Dockerfile
      context: .